# Generated by Django 5.0.2 on 2024-06-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterfile',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
