name: Django Test

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set Environment Variable
        run: echo "LITERAL_APP_ID=github-actions" >> $GITHUB_ENV
      - name: Run make migrations
        run: python manage.py makemigrations
      - name: Run migrations
        run: python manage.py migrate
      - name: Run tests
        run: python manage.py test